// src/Pages/utils/Productdata.js

export const products = [
  {
    id: "1",
    name: "Salicylic Acid Cleanser",
    description: "Dissolves excess oil and clears pores",
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=500",
    severity: "mild",
    type: "cleanser",
    impurity: "whiteheads",
    skinType: "oily",
    area: "face",
    ingredients: ["2% Salicylic Acid", "Niacinamide"],
    effects: ["Clears whiteheads", "Reduces oil", "Prevents future breakouts"],
    usage: "Use twice daily; rinse thoroughly",
    cautions:
      "May cause dryness or irritation. Avoid mixing with strong acids or retinoids.",
    createdAt: "2023-10-01",
  },
  {
    id: "2",
    name: "Benzoyl Peroxide Treatment Gel",
    description: "Treats severe acne and whiteheads",
    image: "https://images.unsplash.com/photo-1611077544417-2fc92be21ccf?w=500",
    severity: "severe",
    type: "treatment",
    impurity: "whiteheads",
    skinType: "oily",
    area: "face",
    ingredients: ["10% Benzoyl Peroxide", "Aloe Vera"],
    effects: [
      "Treats severe breakouts",
      "Reduces inflammation",
      "Clears pores",
    ],
    usage: "Apply thin layer to affected area once daily at night",
    cautions: "Avoid contact with eyes. May bleach fabrics.",
    createdAt: "2023-09-12",
  },
  {
    id: "3",
    name: "Hydrating Cream Cleanser",
    description: "Cleanses while maintaining hydration",
    image: "https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=500",
    severity: "mild",
    type: "cleanser",
    impurity: "whiteheads",
    skinType: "dry",
    area: "face",
    ingredients: ["Hyaluronic Acid", "Aloe Vera"],
    effects: ["Maintains moisture", "Gentle cleanse", "Prevents dryness"],
    usage: "Use morning and night on damp skin.",
    cautions: "For external use only. Discontinue if irritation occurs.",
    createdAt: "2023-08-18",
  },
  {
    id: "4",
    name: "2% BHA Liquid Exfoliant",
    description: "Unclogs pores and prevents whiteheads",
    image: "https://images.unsplash.com/photo-1607435098112-fdbb0c2e667e?w=500",
    severity: "moderate",
    type: "exfoliant",
    impurity: "whiteheads",
    skinType: "oily",
    area: "face",
    ingredients: ["Salicylic Acid", "Green Tea"],
    effects: ["Clears whiteheads", "Controls oil", "Smooths texture"],
    usage: "Use 2–3x per week in PM only; follow with moisturizer",
    cautions: "For external use only. Discontinue if irritation occurs.",
    createdAt: "2023-07-21",
  },
  {
    id: "5",
    name: "Retinoid Cream",
    description: "Clears persistent whiteheads and reduces inflammation",
    image: "https://images.unsplash.com/photo-1617127365659-ecf2932c6d58?w=500",
    severity: "severe",
    type: "treatment",
    impurity: "whiteheads",
    skinType: "normal",
    area: "face",
    ingredients: ["Retinol", "Tretinoin"],
    effects: ["Fights whiteheads", "Improves skin texture", "Reduces acne"],
    usage: "Start with 2–3x/week at night, increase as tolerated",
    cautions:
      "Apply only at night. Use sunscreen during the day. May cause purging.",
    createdAt: "2023-06-03",
  },
  {
    id: "6",
    name: "Glycolic Acid + BHA Toner",
    description: "Exfoliates and clears clogged pores",
    image: "https://images.unsplash.com/photo-1611042553484-5383a234b541?w=500",
    severity: "moderate",
    type: "toner",
    impurity: "pores",
    skinType: "combination",
    area: "face",
    ingredients: ["Glycolic Acid", "Salicylic Acid"],
    effects: ["Refines pores", "Reduces oil", "Prevents acne"],
    usage: "Use 2–3x per week in the evening.",
    cautions: "Do not use on broken or irritated skin. Limit sun exposure.",
    createdAt: "2023-05-10",
  },
  {
    id: "7",
    name: "Soothing Cleansing Foam",
    description: "Gently cleanses and calms irritated skin",
    image: "https://images.unsplash.com/photo-1615397349754-cfa2066a298e?w=500",
    severity: "mild",
    type: "cleanser",
    impurity: "redness",
    skinType: "sensitive",
    area: "face",
    ingredients: ["Chamomile", "Oat Extract"],
    effects: ["Gentle cleanse", "Calms redness", "Hydrates skin"],
    usage: "Use once or twice daily with lukewarm water.",
    cautions: "Patch test recommended for sensitive skin.",
    createdAt: "2023-04-01",
  },
  {
    id: "8",
    name: "Adapalene 0.1% Gel",
    description: "Reduces comedones and prevents new ones",
    image: "https://images.unsplash.com/photo-1620916297397-a4a5402a3c6c?w=500",
    severity: "severe",
    type: "treatment",
    impurity: "blackheads",
    skinType: "combination",
    area: "face",
    ingredients: ["Adapalene"],
    effects: ["Prevents breakouts", "Reduces blackheads", "Smooths skin"],
    usage: "Apply at night; begin 2x/week and increase as tolerated.",
    cautions:
      "Apply only at night. Use sunscreen during the day. May cause purging.",
    createdAt: "2023-03-22",
  },
  {
    id: "9",
    name: "Lactic Acid 5% Serum",
    description: "Gently exfoliates and reduces clogged pores",
    image: "https://images.unsplash.com/photo-1556229010-aa3c453b1af8?w=500",
    severity: "moderate",
    type: "exfoliant",
    impurity: "pores",
    skinType: "dry",
    area: "face",
    ingredients: ["Lactic Acid", "Hyaluronic Acid"],
    effects: ["Removes buildup", "Improves skin texture", "Hydrates"],
    usage: "Use 2–3x per week in PM only.",
    cautions: "Do not use on broken or irritated skin. Limit sun exposure.",
    createdAt: "2023-02-18",
  },
];

export const skinImpurities = [
  "all",
  "pores",
  "redness",
  "wrinkles",
  "blackheads",
  "darkcircles",
  "acne",
  "oil",
  "freckles",
  "whiteheads",
];

export const skinTypes = [
  "all",
  "normal",
  "oily",
  "dry",
  "combination",
  "sensitive",
];

export const sortOptions = [
  { value: "name-asc", label: "Name (A-Z)" },
  { value: "name-desc", label: "Name (Z-A)" },
  { value: "severity-asc", label: "Severity (Mild first)" },
  { value: "severity-desc", label: "Severity (Severe first)" },
  { value: "date-asc", label: "Oldest First" },
  { value: "date-desc", label: "Newest First" },
];

export const getRecommendedProducts = () => {
  return products.slice(0, 7);
};
